# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Reyes-Aldasoro"
title_separator          : "-"
name                     : &name "Constantino Carlos Reyes-Aldasoro"
description              : &description "Biomedical Image Analysis"
url                      : https://reyesaldasoro.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "reyesaldasoro/reyesaldasoro.github.io"
title2                    : "Start page"
title_separator          : "-"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter C_ReyesAldasoro
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles




# Site Author
author:
  name             : "Constantino Carlos Reyes-Aldasoro"
  avatar           : "profile.jpg"
  bio              : "Senior Lecturer in Biomedical Image Analysis at City, University of London"
  location         : "London, United Kingdom"
  employer         :
  pubmed           : "https://pubmed.ncbi.nlm.nih.gov/?term=reyes-aldasoro"
  googlescholar    : "https://scholar.google.co.uk/citations?hl=en&user=DLbXRxoAAAAJ&view_op=list_works"
  email            :
  researchgate     :  "https://www.researchgate.net/profile/Constantino-Reyes-Aldasoro"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "reyesaldasoro"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "https://www.linkedin.com/in/constantino-carlos-reyes-aldasoro-090b822b/"
  orcid            : "https://orcid.org/0000-0002-9466-2018"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : "C_ReyesAldasoro"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :



# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  preprints:
    output: true
    permalink: /:collection/:path/
  bookchapters:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  team:
    output: true
    permalink: /:collection/:path/
  news:
    output: true
    permalink: /:collection/:path/
  techniques:
    output: true
    permalink: /:collection/:path/
  outreach:
    output: true
    permalink: /:collection/:path/
  maintech:
    output: true
    permalink: /:collection/:path/
  mainoutreach:
    output: true
    permalink: /:collection/:path/
  gallery:
    output: true
    permalink: /:collection/:path/
  contact:
    output: true
    permalink: /:collection/:path/
  collaborations:
    output: true
    permalink: /:collection/:path/
  research:
    output: true
    permalink: /:collection/:path/
  resources:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: false
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: false
      comments: true

  # _bookchapters
  - scope:
      path: ""
      type: bookchapters
    values:
      layout: single
      author_profile: true
      share: false
      comments: true

  # _news
  - scope:
      path: ""
      type: news
    values:
      layout: single
      author_profile: true
      share: false
      comments: true

  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: talk
      author_profile: false
      share: false
      comment: true

  # _team
  - scope:
      path: ""
      type: team
    values:
      layout: single
      author_profile: true
      share: false
      comment: true

  # _collaborations
  - scope:
      path: ""
      type: collaborations
    values:
      layout: single
      author_profile: true
      share: false
      comment: true

  # _outreach
  - scope:
      path: ""
      type: outreach
    values:
      layout: talk
      author_profile: false
      share: false
      comment: true

  # _research
  - scope:
      path: ""
      type: research
    values:
      layout: talk
      author_profile: false
      share: false
      comment: true

  # _resources
  - scope:
      path: ""
      type: resources
    values:
      layout: talk
      author_profile: false
      share: false
      comment: true

  # _mainoutreach
  - scope:
      path: ""
      type: mainoutreach
    values:
      layout: talk
      author_profile: false
      share: false
      comment: true

  # _techniques
  - scope:
      path: ""
      type: techniques
    values:
      layout: talk
      author_profile: false
      share: false
      comment: true

  # _gallery
  - scope:
      path: ""
      type: gallery
    values:
      layout: talk
      author_profile: true
      share: false
      comment: true

  # _contact
  - scope:
      path: ""
      type: contact
    values:
      layout: talk
      author_profile: true
      share: false
      comment: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Brussels # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
